* Introduction

  This repository contains the TeX and plain-text source files for the
  "Well Specified Common Lisp" specification.

  "Well Specified Common Lisp" will be abbreviated WSCL, and it should
  be pronounced like "whistle".

  Well Specified Common Lisp has not been published by any standards
  organization and is thus not an official standard, let alone a new
  Common Lisp standard.

  Well Specified Common Lisp is intended as a more strict version of
  the current Common Lisp standard. It is more strict in that it
  attempts to specify required behavior of implementations in many
  cases where the current Common Lisp standard is either silent on the
  subject, or specifically mentions unspecified behavior. We intend to
  accomplish this work in an as uncontroversial way as possible.
  Specifically, we mainly want to consolidate behavior that most
  existing Common Lisp implementations already agree upon.

* Content

  + file:dpANS3 directory ::

       This directory contains the TeX sources of the final draft of
       the Common Lisp specification with two kinds of changes:

       1. Modifications to make the TeX sources syntactically correct
          and internally consistent without affecting the semantics.

       2. Modifications due to the application of passed WSCL cleanup
          issues.

  + file:x3j13-issues directory ::

       This directory contains a subset of the X3J13 cleanup issues
       produced by the committee.

       The files in this directory have been obtained from
       http://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/lisp/doc/standard/ansi/cleanup/
       on 2021-05-06. Unfortunately, that collection does not contain
       all issue files.

  + file:wscl-issues directory ::

       This directory contains cleanup issues which describe changes
       that produce the WSCL specification from the final draft of the
       Common Lisp specification.

  + file:changes directory ::

       This directory contains descriptions of changes that were made
       to the TeX sources of the final draft of the Common Lisp
       specification as well as the X3J13 cleanup issues.
